import {
  Organization,
  Employee,
  Department,
  Team,
  LeaveTypePolicy,
  LeaveRequest,
  AttendanceRecord,
  WorkShift,
  AttendanceRules,
  PayrollRun,
  Announcement,
  KnowledgeBaseCategory,
  KnowledgeBaseArticle,
  AuditLog,
  TenantNotification,
  SubscriptionInvoice,
  TimesheetCorrectionRequest,
  TeamMemberTimesheet,
  TeamSpacePost,
} from "./types";

export const initialOrganizations: Organization[] = [
  {
    id: "org-roacs",
    name: "Roacs Corporation",
    logo: "RC",
    industry: "Enterprise Software & Cloud AI",
    size: "100-250 Employees",
    address: "742 Innovation Way, Suite 400, San Francisco, CA 94105",
    country: "United States",
    timezone: "UTC-07:00 (Pacific Time)",
    currency: "USD ($)",
    financialYear: "January - December",
    workingWeek: "Monday - Friday",
    plan: "Professional",
    employeeLimit: 200,
    subscriptionStatus: "Active",
    billingCycle: "Annual",
    monthlyCost: 499,
    renewalDate: "2027-01-15",
    startDate: "2025-01-15",
  },
  {
    id: "org-acme",
    name: "Acme Innovations Ltd",
    logo: "AI",
    industry: "Financial Advisory & Research",
    size: "10-50 Employees",
    address: "18 Wall Street, 12th Floor, New York, NY 10005",
    country: "United States",
    timezone: "UTC-05:00 (Eastern Time)",
    currency: "USD ($)",
    financialYear: "April - March",
    workingWeek: "Monday - Friday",
    plan: "Starter",
    employeeLimit: 25, // Currently at 24 - adding 2 employees triggers the limit block!
    subscriptionStatus: "Active",
    billingCycle: "Monthly",
    monthlyCost: 99,
    renewalDate: "2026-10-01",
    startDate: "2026-04-01",
  },
];

export const initialDepartments: Department[] = [
  { id: "dept-eng", organizationId: "org-roacs", name: "Engineering", headEmployeeId: "emp-102", headEmployeeName: "David Chen", memberCount: 64 },
  { id: "dept-prod", organizationId: "org-roacs", name: "Product & Design", headEmployeeId: "emp-101", headEmployeeName: "Sophia Williams", memberCount: 31 },
  { id: "dept-sales", organizationId: "org-roacs", name: "Sales & Growth", headEmployeeId: "emp-106", headEmployeeName: "Elena Rostova", memberCount: 24 },
  { id: "dept-ops", organizationId: "org-roacs", name: "Operations & HR", headEmployeeId: "emp-104", headEmployeeName: "Amira Patel", memberCount: 15 },
  { id: "dept-fin", organizationId: "org-roacs", name: "Finance & Legal", headEmployeeId: "emp-107", headEmployeeName: "Michael Chang", memberCount: 8 },

  // Acme Depts
  { id: "dept-acme-adv", organizationId: "org-acme", name: "Client Advisory", headEmployeeId: "emp-acme-1", headEmployeeName: "Arthur Sterling", memberCount: 14 },
  { id: "dept-acme-res", organizationId: "org-acme", name: "Market Research", headEmployeeId: "emp-acme-2", headEmployeeName: "Clara Oswald", memberCount: 10 },
];

export const initialTeams: Team[] = [
  { id: "team-fe", organizationId: "org-roacs", departmentId: "dept-eng", departmentName: "Engineering", name: "Frontend Platform", leadEmployeeId: "emp-103", leadEmployeeName: "Liam O'Connor", memberCount: 18 },
  { id: "team-be", organizationId: "org-roacs", departmentId: "dept-eng", departmentName: "Engineering", name: "Core Backend & Infra", leadEmployeeId: "emp-102", leadEmployeeName: "David Chen", memberCount: 26 },
  { id: "team-design", organizationId: "org-roacs", departmentId: "dept-prod", departmentName: "Product & Design", name: "UX & Product Systems", leadEmployeeId: "emp-101", leadEmployeeName: "Sophia Williams", memberCount: 14 },
  { id: "team-people", organizationId: "org-roacs", departmentId: "dept-ops", departmentName: "Operations & HR", name: "Talent & Culture", leadEmployeeId: "emp-104", leadEmployeeName: "Amira Patel", memberCount: 7 },
  
  // Acme Teams
  { id: "team-acme-wealth", organizationId: "org-acme", departmentId: "dept-acme-adv", departmentName: "Client Advisory", name: "Wealth Management", leadEmployeeId: "emp-acme-1", leadEmployeeName: "Arthur Sterling", memberCount: 8 },
];

export const initialEmployees: Employee[] = [
  {
    id: "emp-101",
    organizationId: "org-roacs",
    employeeId: "RC-101",
    firstName: "Sophia",
    lastName: "Williams",
    name: "Sophia Williams",
    email: "sophia.w@roacscorp.com",
    personalEmail: "sophia.williams.design@gmail.com",
    phone: "+1 (555) 234-5678",
    avatar: "SW",
    dateOfBirth: "1991-04-14",
    gender: "Female",
    address: "128 Pine St, Apt 4B, San Francisco, CA",
    emergencyContact: {
      name: "Thomas Williams",
      relationship: "Spouse",
      phone: "+1 (555) 234-9988",
    },
    department: "Product & Design",
    designation: "Lead UI/UX Designer",
    team: "UX & Product Systems",
    assignedTLId: "emp-101",
    assignedTLName: "Sophia Williams (Self-Lead)",
    assignedManagerId: "emp-104",
    assignedManagerName: "Amira Patel",
    employmentType: "Full Time",
    workLocation: "San Francisco HQ (Hybrid)",
    joiningDate: "2022-03-15",
    probationEndDate: "2022-06-15",
    status: "Active",
    role: "manager",
    compensation: {
      basicSalary: 6200,
      hra: 1800,
      allowances: 600,
      specialAllowance: 400,
      bonus: 800,
      incentives: 0,
      overtime: 0,
      tax: 1250,
      pf: 450,
      insurance: 150,
      otherDeductions: 50,
      currency: "USD",
      paymentMethod: "Bank Transfer",
      bankName: "Silicon Valley Bank",
      accountNumber: "•••• 4821",
      routingCode: "121000358",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 15, used: 4, pending: 3, remaining: 8 },
      { leaveTypeId: "lt-casual", leaveTypeName: "Casual Leave", allocated: 10, used: 2, pending: 0, remaining: 8 },
      { leaveTypeId: "lt-sick", leaveTypeName: "Sick Leave", allocated: 12, used: 1, pending: 0, remaining: 11 },
    ],
    createdAt: "2022-03-15T09:00:00Z",
    updatedAt: "2026-08-20T14:30:00Z",
  },
  {
    id: "emp-102",
    organizationId: "org-roacs",
    employeeId: "RC-102",
    firstName: "David",
    lastName: "Chen",
    name: "David Chen",
    email: "david.c@roacscorp.com",
    personalEmail: "davidchen.dev@outlook.com",
    phone: "+1 (555) 345-6789",
    avatar: "DC",
    dateOfBirth: "1988-11-23",
    gender: "Male",
    address: "450 Fremont Blvd, Fremont, CA",
    emergencyContact: {
      name: "Helen Chen",
      relationship: "Sister",
      phone: "+1 (555) 345-0012",
    },
    department: "Engineering",
    designation: "Senior Fullstack Engineer",
    team: "Core Backend & Infra",
    assignedTLId: "emp-102",
    assignedTLName: "David Chen",
    assignedManagerId: "emp-104",
    assignedManagerName: "Amira Patel",
    employmentType: "Full Time",
    workLocation: "San Francisco HQ (On-site)",
    joiningDate: "2021-08-01",
    status: "Active",
    role: "team-lead",
    compensation: {
      basicSalary: 7500,
      hra: 2200,
      allowances: 800,
      specialAllowance: 500,
      bonus: 1000,
      incentives: 0,
      overtime: 320,
      tax: 1680,
      pf: 550,
      insurance: 180,
      otherDeductions: 60,
      currency: "USD",
      paymentMethod: "Bank Transfer",
      bankName: "Chase Bank",
      accountNumber: "•••• 9143",
      routingCode: "021000021",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 15, used: 6, pending: 0, remaining: 9 },
      { leaveTypeId: "lt-casual", leaveTypeName: "Casual Leave", allocated: 10, used: 3, pending: 0, remaining: 7 },
      { leaveTypeId: "lt-sick", leaveTypeName: "Sick Leave", allocated: 12, used: 2, pending: 0, remaining: 10 },
    ],
    createdAt: "2021-08-01T09:00:00Z",
    updatedAt: "2026-09-01T10:15:00Z",
  },
  {
    id: "emp-103",
    organizationId: "org-roacs",
    employeeId: "RC-103",
    firstName: "Liam",
    lastName: "O'Connor",
    name: "Liam O'Connor",
    email: "liam.o@roacscorp.com",
    personalEmail: "liam.oconnor.qa@gmail.com",
    phone: "+1 (555) 456-7890",
    avatar: "LO",
    dateOfBirth: "1994-06-18",
    gender: "Male",
    address: "89 Market St, San Francisco, CA",
    emergencyContact: {
      name: "Patrick O'Connor",
      relationship: "Father",
      phone: "+1 (555) 456-1122",
    },
    department: "Engineering",
    designation: "QA Automation Engineer",
    team: "Frontend Platform",
    assignedTLId: "emp-102",
    assignedTLName: "David Chen",
    assignedManagerId: "emp-104",
    assignedManagerName: "Amira Patel",
    employmentType: "Full Time",
    workLocation: "Remote (USA)",
    joiningDate: "2023-01-10",
    status: "Active",
    role: "employee",
    compensation: {
      basicSalary: 5200,
      hra: 1500,
      allowances: 500,
      specialAllowance: 300,
      bonus: 400,
      incentives: 0,
      overtime: 150,
      tax: 980,
      pf: 380,
      insurance: 140,
      otherDeductions: 40,
      currency: "USD",
      paymentMethod: "Direct Deposit",
      bankName: "Wells Fargo",
      accountNumber: "•••• 3390",
      routingCode: "121000248",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 15, used: 2, pending: 0, remaining: 13 },
      { leaveTypeId: "lt-casual", leaveTypeName: "Casual Leave", allocated: 10, used: 1, pending: 0, remaining: 9 },
      { leaveTypeId: "lt-sick", leaveTypeName: "Sick Leave", allocated: 12, used: 0, pending: 0, remaining: 12 },
    ],
    createdAt: "2023-01-10T09:00:00Z",
    updatedAt: "2026-08-15T11:00:00Z",
  },
  {
    id: "emp-104",
    organizationId: "org-roacs",
    employeeId: "RC-104",
    firstName: "Amira",
    lastName: "Patel",
    name: "Amira Patel",
    email: "amira.p@roacscorp.com",
    personalEmail: "amira.patel.hr@gmail.com",
    phone: "+1 (555) 567-8901",
    avatar: "AP",
    dateOfBirth: "1989-09-29",
    gender: "Female",
    address: "210 Bush St, San Francisco, CA",
    emergencyContact: {
      name: "Rajesh Patel",
      relationship: "Brother",
      phone: "+1 (555) 567-3344",
    },
    department: "Operations & HR",
    designation: "HR Operations Director",
    team: "Talent & Culture",
    assignedTLId: "emp-104",
    assignedTLName: "Amira Patel (Lead)",
    assignedManagerId: "emp-104",
    assignedManagerName: "Executive Committee",
    employmentType: "Full Time",
    workLocation: "San Francisco HQ (On-site)",
    joiningDate: "2020-11-01",
    status: "Active",
    role: "admin-hr",
    compensation: {
      basicSalary: 6800,
      hra: 2000,
      allowances: 700,
      specialAllowance: 500,
      bonus: 750,
      incentives: 0,
      overtime: 0,
      tax: 1420,
      pf: 500,
      insurance: 160,
      otherDeductions: 50,
      currency: "USD",
      paymentMethod: "Bank Transfer",
      bankName: "Bank of America",
      accountNumber: "•••• 7712",
      routingCode: "121000358",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 15, used: 5, pending: 0, remaining: 10 },
      { leaveTypeId: "lt-casual", leaveTypeName: "Casual Leave", allocated: 10, used: 2, pending: 0, remaining: 8 },
      { leaveTypeId: "lt-sick", leaveTypeName: "Sick Leave", allocated: 12, used: 1, pending: 0, remaining: 11 },
    ],
    createdAt: "2020-11-01T09:00:00Z",
    updatedAt: "2026-09-02T16:20:00Z",
  },
  {
    id: "emp-105",
    organizationId: "org-roacs",
    employeeId: "RC-105",
    firstName: "Carlos",
    lastName: "Mendez",
    name: "Carlos Mendez",
    email: "carlos.m@roacscorp.com",
    personalEmail: "carlos.mendez.dev@gmail.com",
    phone: "+1 (555) 678-9012",
    avatar: "CM",
    dateOfBirth: "1996-12-05",
    gender: "Male",
    address: "330 2nd St, Oakland, CA",
    emergencyContact: {
      name: "Maria Mendez",
      relationship: "Mother",
      phone: "+1 (555) 678-5566",
    },
    department: "Engineering",
    designation: "Junior Cloud Engineer",
    team: "Core Backend & Infra",
    assignedTLId: "emp-102",
    assignedTLName: "David Chen",
    assignedManagerId: "emp-104",
    assignedManagerName: "Amira Patel",
    employmentType: "Full Time",
    workLocation: "San Francisco HQ (Hybrid)",
    joiningDate: "2026-07-01",
    probationEndDate: "2026-10-01",
    status: "Probation",
    role: "employee",
    compensation: {
      basicSalary: 4500,
      hra: 1200,
      allowances: 400,
      specialAllowance: 200,
      bonus: 0,
      incentives: 0,
      overtime: 80,
      tax: 720,
      pf: 320,
      insurance: 120,
      otherDeductions: 30,
      currency: "USD",
      paymentMethod: "Bank Transfer",
      bankName: "Capital One",
      accountNumber: "•••• 6209",
      routingCode: "051405515",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 15, used: 1, pending: 0, remaining: 14 },
      { leaveTypeId: "lt-casual", leaveTypeName: "Casual Leave", allocated: 10, used: 0, pending: 0, remaining: 10 },
      { leaveTypeId: "lt-sick", leaveTypeName: "Sick Leave", allocated: 12, used: 1, pending: 0, remaining: 11 },
    ],
    createdAt: "2026-07-01T09:00:00Z",
    updatedAt: "2026-09-04T12:00:00Z",
  },
  {
    id: "emp-106",
    organizationId: "org-roacs",
    employeeId: "RC-106",
    firstName: "Elena",
    lastName: "Rostova",
    name: "Elena Rostova",
    email: "elena.r@roacscorp.com",
    personalEmail: "elena.rostova@gmail.com",
    phone: "+1 (555) 789-0123",
    avatar: "ER",
    dateOfBirth: "1992-09-12",
    gender: "Female",
    address: "710 Battery St, San Francisco, CA",
    emergencyContact: {
      name: "Sergei Rostov",
      relationship: "Father",
      phone: "+1 (555) 789-7788",
    },
    department: "Sales & Growth",
    designation: "Senior Account Executive",
    team: "Sales & Growth",
    assignedTLId: "emp-106",
    assignedTLName: "Elena Rostova",
    assignedManagerId: "emp-104",
    assignedManagerName: "Amira Patel",
    employmentType: "Full Time",
    workLocation: "San Francisco HQ (Hybrid)",
    joiningDate: "2023-09-12",
    status: "Active",
    role: "team-lead",
    compensation: {
      basicSalary: 5800,
      hra: 1600,
      allowances: 600,
      specialAllowance: 400,
      bonus: 1200,
      incentives: 950,
      overtime: 0,
      tax: 1350,
      pf: 420,
      insurance: 150,
      otherDeductions: 50,
      currency: "USD",
      paymentMethod: "Bank Transfer",
      bankName: "Citibank",
      accountNumber: "•••• 1984",
      routingCode: "021000089",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 15, used: 3, pending: 0, remaining: 12 },
      { leaveTypeId: "lt-casual", leaveTypeName: "Casual Leave", allocated: 10, used: 1, pending: 0, remaining: 9 },
      { leaveTypeId: "lt-sick", leaveTypeName: "Sick Leave", allocated: 12, used: 0, pending: 0, remaining: 12 },
    ],
    createdAt: "2023-09-12T09:00:00Z",
    updatedAt: "2026-09-05T14:10:00Z",
  },
  {
    id: "emp-107",
    organizationId: "org-roacs",
    employeeId: "RC-107",
    firstName: "Michael",
    lastName: "Chang",
    name: "Michael Chang",
    email: "michael.c@roacscorp.com",
    personalEmail: "m.chang.fin@outlook.com",
    phone: "+1 (555) 890-1234",
    avatar: "MC",
    dateOfBirth: "1985-02-28",
    gender: "Male",
    address: "555 California St, San Francisco, CA",
    emergencyContact: {
      name: "Grace Chang",
      relationship: "Spouse",
      phone: "+1 (555) 890-9900",
    },
    department: "Finance & Legal",
    designation: "Finance Director",
    team: "Finance & Legal",
    assignedTLId: "emp-107",
    assignedTLName: "Michael Chang",
    assignedManagerId: "emp-104",
    assignedManagerName: "Amira Patel",
    employmentType: "Full Time",
    workLocation: "San Francisco HQ (On-site)",
    joiningDate: "2020-04-01",
    status: "Active",
    role: "manager",
    compensation: {
      basicSalary: 8200,
      hra: 2400,
      allowances: 900,
      specialAllowance: 600,
      bonus: 1500,
      incentives: 0,
      overtime: 0,
      tax: 1950,
      pf: 600,
      insurance: 200,
      otherDeductions: 70,
      currency: "USD",
      paymentMethod: "Bank Transfer",
      bankName: "JPMorgan Chase",
      accountNumber: "•••• 8234",
      routingCode: "021000021",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 15, used: 7, pending: 0, remaining: 8 },
      { leaveTypeId: "lt-casual", leaveTypeName: "Casual Leave", allocated: 10, used: 2, pending: 0, remaining: 8 },
      { leaveTypeId: "lt-sick", leaveTypeName: "Sick Leave", allocated: 12, used: 2, pending: 0, remaining: 10 },
    ],
    createdAt: "2020-04-01T09:00:00Z",
    updatedAt: "2026-08-30T10:00:00Z",
  },
  {
    id: "emp-108",
    organizationId: "org-roacs",
    employeeId: "RC-108",
    firstName: "Rachel",
    lastName: "Kim",
    name: "Rachel Kim",
    email: "rachel.k@roacscorp.com",
    personalEmail: "rachel.kim.growth@gmail.com",
    phone: "+1 (555) 901-2345",
    avatar: "RK",
    dateOfBirth: "1997-08-19",
    gender: "Female",
    address: "1024 Grand Ave, South San Francisco, CA",
    emergencyContact: {
      name: "Daniel Kim",
      relationship: "Brother",
      phone: "+1 (555) 901-4455",
    },
    department: "Sales & Growth",
    designation: "Growth Marketing Specialist",
    team: "Sales & Growth",
    assignedTLId: "emp-106",
    assignedTLName: "Elena Rostova",
    assignedManagerId: "emp-104",
    assignedManagerName: "Amira Patel",
    employmentType: "Contract",
    workLocation: "Remote (USA)",
    joiningDate: "2024-05-15",
    status: "Notice Period",
    role: "employee",
    compensation: {
      basicSalary: 4800,
      hra: 1300,
      allowances: 450,
      specialAllowance: 250,
      bonus: 300,
      incentives: 400,
      overtime: 0,
      tax: 910,
      pf: 350,
      insurance: 130,
      otherDeductions: 40,
      currency: "USD",
      paymentMethod: "Direct Deposit",
      bankName: "US Bank",
      accountNumber: "•••• 4410",
      routingCode: "123000220",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 15, used: 8, pending: 0, remaining: 7 },
      { leaveTypeId: "lt-casual", leaveTypeName: "Casual Leave", allocated: 10, used: 4, pending: 0, remaining: 6 },
      { leaveTypeId: "lt-sick", leaveTypeName: "Sick Leave", allocated: 12, used: 1, pending: 0, remaining: 11 },
    ],
    createdAt: "2024-05-15T09:00:00Z",
    updatedAt: "2026-09-03T15:45:00Z",
  },
  {
    id: "emp-109",
    organizationId: "org-roacs",
    employeeId: "RC-109",
    firstName: "Tariq",
    lastName: "Mansour",
    name: "Tariq Mansour",
    email: "tariq.m@roacscorp.com",
    personalEmail: "tariq.mansour.old@gmail.com",
    phone: "+1 (555) 912-3456",
    avatar: "TM",
    dateOfBirth: "1990-03-11",
    gender: "Male",
    address: "650 Mission St, San Francisco, CA",
    emergencyContact: {
      name: "Fatima Mansour",
      relationship: "Spouse",
      phone: "+1 (555) 912-8899",
    },
    department: "Engineering",
    designation: "DevOps Engineer",
    team: "Core Backend & Infra",
    assignedTLId: "emp-102",
    assignedTLName: "David Chen",
    assignedManagerId: "emp-104",
    assignedManagerName: "Amira Patel",
    employmentType: "Full Time",
    workLocation: "San Francisco HQ (On-site)",
    joiningDate: "2022-10-01",
    status: "Offboarded",
    role: "employee",
    compensation: {
      basicSalary: 6400,
      hra: 1900,
      allowances: 650,
      specialAllowance: 400,
      bonus: 0,
      incentives: 0,
      overtime: 0,
      tax: 1280,
      pf: 460,
      insurance: 150,
      otherDeductions: 50,
      currency: "USD",
      paymentMethod: "Bank Transfer",
      bankName: "First Republic",
      accountNumber: "•••• 5521",
      routingCode: "121000358",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 15, used: 12, pending: 0, remaining: 3 },
      { leaveTypeId: "lt-casual", leaveTypeName: "Casual Leave", allocated: 10, used: 8, pending: 0, remaining: 2 },
      { leaveTypeId: "lt-sick", leaveTypeName: "Sick Leave", allocated: 12, used: 4, pending: 0, remaining: 8 },
    ],
    offboardingDetails: {
      lastWorkingDate: "2026-08-31",
      reason: "Relocating abroad to pursue academic sabbatical",
      noticePeriod: "30 Days",
      exitInterviewRequired: true,
      finalSettlementRequired: true,
      disableAccountDate: "2026-08-31",
      assetReturnStatus: "Completed",
      remarks: "Returned MacBook Pro M3, security badge, and company monitor in excellent condition. Final settlement disbursed on Sep 1, 2026.",
      offboardedAt: "2026-08-31T17:00:00Z",
    },
    createdAt: "2022-10-01T09:00:00Z",
    updatedAt: "2026-08-31T17:00:00Z",
  },

  // Acme Employees (Tenant Isolation Demo)
  {
    id: "emp-acme-1",
    organizationId: "org-acme",
    employeeId: "AI-001",
    firstName: "Arthur",
    lastName: "Sterling",
    name: "Arthur Sterling",
    email: "arthur.s@acmeinnovations.com",
    personalEmail: "arthur.sterling@nyu.edu",
    phone: "+1 (212) 555-0199",
    avatar: "AS",
    dateOfBirth: "1982-05-14",
    gender: "Male",
    address: "740 Park Ave, New York, NY",
    emergencyContact: {
      name: "Victoria Sterling",
      relationship: "Spouse",
      phone: "+1 (212) 555-0188",
    },
    department: "Client Advisory",
    designation: "Managing Director",
    team: "Wealth Management",
    assignedTLId: "emp-acme-1",
    assignedTLName: "Arthur Sterling",
    employmentType: "Full Time",
    workLocation: "New York HQ",
    joiningDate: "2021-02-01",
    status: "Active",
    role: "admin-hr",
    compensation: {
      basicSalary: 9500,
      hra: 2500,
      allowances: 1000,
      specialAllowance: 800,
      bonus: 2000,
      incentives: 1500,
      overtime: 0,
      tax: 2800,
      pf: 700,
      insurance: 250,
      otherDeductions: 100,
      currency: "USD",
      paymentMethod: "Bank Transfer",
      bankName: "Goldman Sachs Bank USA",
      accountNumber: "•••• 7812",
      routingCode: "021000089",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 20, used: 6, pending: 0, remaining: 14 },
    ],
    createdAt: "2021-02-01T09:00:00Z",
    updatedAt: "2026-08-10T12:00:00Z",
  },
  {
    id: "emp-acme-2",
    organizationId: "org-acme",
    employeeId: "AI-002",
    firstName: "Clara",
    lastName: "Oswald",
    name: "Clara Oswald",
    email: "clara.o@acmeinnovations.com",
    personalEmail: "clara.oswald@gmail.com",
    phone: "+1 (212) 555-0244",
    avatar: "CO",
    dateOfBirth: "1993-11-23",
    gender: "Female",
    address: "420 Columbus Ave, New York, NY",
    emergencyContact: {
      name: "Dave Oswald",
      relationship: "Father",
      phone: "+1 (212) 555-0200",
    },
    department: "Market Research",
    designation: "Quantitative Analyst",
    team: "Market Research",
    assignedTLId: "emp-acme-1",
    assignedTLName: "Arthur Sterling",
    employmentType: "Full Time",
    workLocation: "New York HQ",
    joiningDate: "2023-05-15",
    status: "Active",
    role: "employee",
    compensation: {
      basicSalary: 7200,
      hra: 1800,
      allowances: 600,
      specialAllowance: 400,
      bonus: 1000,
      incentives: 500,
      overtime: 0,
      tax: 1650,
      pf: 520,
      insurance: 180,
      otherDeductions: 60,
      currency: "USD",
      paymentMethod: "Direct Deposit",
      bankName: "Morgan Stanley Private Bank",
      accountNumber: "•••• 3920",
      routingCode: "021000021",
    },
    leaveBalances: [
      { leaveTypeId: "lt-annual", leaveTypeName: "Annual Leave", allocated: 20, used: 4, pending: 0, remaining: 16 },
    ],
    createdAt: "2023-05-15T09:00:00Z",
    updatedAt: "2026-08-22T10:00:00Z",
  },
];

export const initialLeavePolicies: LeaveTypePolicy[] = [
  {
    id: "lt-annual",
    organizationId: "org-roacs",
    name: "Annual Leave",
    code: "AL",
    annualAllocation: 15,
    paid: true,
    carryForward: true,
    maxCarryForward: 5,
    accrualType: "Annual Upfront",
    maxConsecutiveDays: 10,
    minNoticePeriod: 7,
    attachmentRequired: false,
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    genderRestriction: "All",
    employmentTypeEligibility: ["Full Time", "Part Time"],
    status: "Active",
    effectiveDate: "Immediate",
  },
  {
    id: "lt-casual",
    organizationId: "org-roacs",
    name: "Casual Leave",
    code: "CL",
    annualAllocation: 10,
    paid: true,
    carryForward: false,
    maxCarryForward: 0,
    accrualType: "Annual Upfront",
    maxConsecutiveDays: 3,
    minNoticePeriod: 1,
    attachmentRequired: false,
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    genderRestriction: "All",
    employmentTypeEligibility: ["Full Time", "Part Time", "Contract"],
    status: "Active",
    effectiveDate: "Immediate",
  },
  {
    id: "lt-sick",
    organizationId: "org-roacs",
    name: "Sick Leave",
    code: "SL",
    annualAllocation: 12,
    paid: true,
    carryForward: true,
    maxCarryForward: 6,
    accrualType: "Monthly Accrual",
    maxConsecutiveDays: 5,
    minNoticePeriod: 0,
    attachmentRequired: true,
    halfDayAllowed: true,
    negativeBalanceAllowed: true,
    genderRestriction: "All",
    employmentTypeEligibility: ["Full Time", "Part Time", "Contract", "Intern"],
    status: "Active",
    effectiveDate: "Immediate",
  },
  {
    id: "lt-maternity",
    organizationId: "org-roacs",
    name: "Maternity / Parental Leave",
    code: "ML",
    annualAllocation: 84,
    paid: true,
    carryForward: false,
    maxCarryForward: 0,
    accrualType: "Annual Upfront",
    maxConsecutiveDays: 84,
    minNoticePeriod: 30,
    attachmentRequired: true,
    halfDayAllowed: false,
    negativeBalanceAllowed: false,
    genderRestriction: "All",
    employmentTypeEligibility: ["Full Time"],
    status: "Active",
    effectiveDate: "Immediate",
  },
  {
    id: "lt-unpaid",
    organizationId: "org-roacs",
    name: "Leave Without Pay (Loss of Pay)",
    code: "LOP",
    annualAllocation: 30,
    paid: false,
    carryForward: false,
    maxCarryForward: 0,
    accrualType: "Annual Upfront",
    maxConsecutiveDays: 30,
    minNoticePeriod: 3,
    attachmentRequired: false,
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    genderRestriction: "All",
    employmentTypeEligibility: ["Full Time", "Part Time", "Contract", "Intern", "Consultant"],
    status: "Active",
    effectiveDate: "Immediate",
  },

  // Acme Policies
  {
    id: "lt-acme-pto",
    organizationId: "org-acme",
    name: "Executive Paid Time Off",
    code: "PTO",
    annualAllocation: 25,
    paid: true,
    carryForward: true,
    maxCarryForward: 10,
    accrualType: "Annual Upfront",
    maxConsecutiveDays: 15,
    minNoticePeriod: 5,
    attachmentRequired: false,
    halfDayAllowed: true,
    negativeBalanceAllowed: false,
    employmentTypeEligibility: ["Full Time"],
    status: "Active",
    effectiveDate: "Immediate",
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "lr-101",
    organizationId: "org-roacs",
    employeeId: "emp-101",
    employeeName: "Sophia Williams",
    employeeAvatar: "SW",
    leaveTypeId: "lt-annual",
    leaveTypeName: "Annual Leave",
    startDate: "2026-09-08",
    endDate: "2026-09-10",
    days: 3,
    reason: "Family vacation & mountain cabin retreat",
    status: "Pending",
    appliedAt: "2026-09-06T10:30:00Z",
  },
  {
    id: "lr-102",
    organizationId: "org-roacs",
    employeeId: "emp-105",
    employeeName: "Carlos Mendez",
    employeeAvatar: "CM",
    leaveTypeId: "lt-sick",
    leaveTypeName: "Sick Leave",
    startDate: "2026-09-04",
    endDate: "2026-09-04",
    days: 1,
    reason: "Severe dental checkup and root canal appointment",
    status: "Approved",
    appliedAt: "2026-09-03T18:20:00Z",
    reviewedBy: "David Chen",
    reviewedAt: "2026-09-03T20:10:00Z",
  },
  {
    id: "lr-103",
    organizationId: "org-roacs",
    employeeId: "emp-108",
    employeeName: "Rachel Kim",
    employeeAvatar: "RK",
    leaveTypeId: "lt-casual",
    leaveTypeName: "Casual Leave",
    startDate: "2026-09-15",
    endDate: "2026-09-16",
    days: 2,
    reason: "Apartment moving & lease signing",
    status: "Pending",
    appliedAt: "2026-09-05T14:40:00Z",
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  { id: "att-1", organizationId: "org-roacs", employeeId: "emp-101", employeeName: "Sophia Williams", date: "2026-09-07", checkIn: "08:58 AM", checkOut: "06:05 PM", status: "Present", workHours: 8.5, overtimeHours: 0 },
  { id: "att-2", organizationId: "org-roacs", employeeId: "emp-102", employeeName: "David Chen", date: "2026-09-07", checkIn: "08:45 AM", checkOut: "07:15 PM", status: "Present", workHours: 9.5, overtimeHours: 1.5 },
  { id: "att-3", organizationId: "org-roacs", employeeId: "emp-103", employeeName: "Liam O'Connor", date: "2026-09-07", checkIn: "09:05 AM", checkOut: "06:10 PM", status: "Present", workHours: 8.0, overtimeHours: 0 },
  { id: "att-4", organizationId: "org-roacs", employeeId: "emp-104", employeeName: "Amira Patel", date: "2026-09-07", checkIn: "08:50 AM", checkOut: "06:00 PM", status: "Present", workHours: 8.2, overtimeHours: 0 },
  { id: "att-5", organizationId: "org-roacs", employeeId: "emp-105", employeeName: "Carlos Mendez", date: "2026-09-07", checkIn: "09:22 AM", checkOut: "06:00 PM", status: "Late", workHours: 7.6, overtimeHours: 0 },
  { id: "att-6", organizationId: "org-roacs", employeeId: "emp-106", employeeName: "Elena Rostova", date: "2026-09-07", checkIn: "09:00 AM", checkOut: "06:30 PM", status: "Present", workHours: 8.5, overtimeHours: 0.5 },
  { id: "att-7", organizationId: "org-roacs", employeeId: "emp-107", employeeName: "Michael Chang", date: "2026-09-07", checkIn: "08:40 AM", checkOut: "06:15 PM", status: "Present", workHours: 8.6, overtimeHours: 0 },
  { id: "att-8", organizationId: "org-roacs", employeeId: "emp-108", employeeName: "Rachel Kim", date: "2026-09-07", status: "On Leave", workHours: 0, overtimeHours: 0 },
];

export const initialWorkShifts: WorkShift[] = [
  {
    id: "shift-general",
    organizationId: "org-roacs",
    name: "General Corporate Shift",
    startTime: "09:00 AM",
    endTime: "06:00 PM",
    gracePeriodMinutes: 15,
    minWorkingHours: 8,
    halfDayWorkingHours: 4,
    breakDurationMinutes: 60,
    weeklyOffDays: ["Saturday", "Sunday"],
    isNightShift: false,
    assignedTo: { type: "Company" },
  },
  {
    id: "shift-morning-ops",
    organizationId: "org-roacs",
    name: "Morning Operations Shift",
    startTime: "07:30 AM",
    endTime: "04:30 PM",
    gracePeriodMinutes: 10,
    minWorkingHours: 8,
    halfDayWorkingHours: 4,
    breakDurationMinutes: 60,
    weeklyOffDays: ["Saturday", "Sunday"],
    isNightShift: false,
    assignedTo: { type: "Department", targetId: "dept-ops", targetName: "Operations & HR" },
  },
  {
    id: "shift-engineering-night",
    organizationId: "org-roacs",
    name: "On-Call Engineering Support Shift",
    startTime: "08:00 PM",
    endTime: "05:00 AM",
    gracePeriodMinutes: 20,
    minWorkingHours: 8,
    halfDayWorkingHours: 4,
    breakDurationMinutes: 60,
    weeklyOffDays: ["Saturday", "Sunday"],
    isNightShift: true,
    assignedTo: { type: "Team", targetId: "team-be", targetName: "Core Backend & Infra" },
  },

  // Acme Shift
  {
    id: "shift-acme-standard",
    organizationId: "org-acme",
    name: "Wall St Standard Hours",
    startTime: "08:30 AM",
    endTime: "05:30 PM",
    gracePeriodMinutes: 15,
    minWorkingHours: 8,
    halfDayWorkingHours: 4,
    breakDurationMinutes: 60,
    weeklyOffDays: ["Saturday", "Sunday"],
    isNightShift: false,
    assignedTo: { type: "Company" },
  },
];

export const initialAttendanceRules: AttendanceRules = {
  id: "ar-roacs",
  organizationId: "org-roacs",
  checkInRequired: true,
  checkOutRequired: true,
  gracePeriodMinutes: 15,
  lateMarkRule: "3 late arrivals within a calendar month deduct 0.5 days from Casual Leave",
  halfDayRule: "Less than 4.5 hours worked in a single shift is logged as Half-Day",
  minWorkingHours: 8.0,
  overtimeEnabled: true,
  weekendWorkingAllowed: true,
  wfhAllowed: true,
  regularizationAllowed: true,
  geoLocationRequired: false,
  ipRestrictionEnabled: false,
  allowedIps: ["192.168.1.0/24", "10.0.0.1/16"],
};

export const initialPayrollRuns: PayrollRun[] = [
  {
    id: "pr-2026-08",
    organizationId: "org-roacs",
    month: "August",
    year: 2026,
    status: "Paid",
    totalEmployees: 8,
    workingDays: 22,
    grossPayroll: 50400,
    totalBonuses: 5650,
    totalDeductions: 13420,
    taxDeductions: 9310,
    netPayroll: 42630,
    processedAt: "2026-08-28T14:00:00Z",
    approvedAt: "2026-08-29T10:30:00Z",
    paidAt: "2026-08-31T09:00:00Z",
    lockedAt: "2026-08-31T18:00:00Z",
    items: [
      {
        id: "pi-101",
        payrollRunId: "pr-2026-08",
        organizationId: "org-roacs",
        employeeId: "emp-101",
        employeeName: "Sophia Williams",
        employeeCode: "RC-101",
        department: "Product & Design",
        designation: "Lead UI/UX Designer",
        basicSalary: 6200,
        hra: 1800,
        allowances: 600,
        specialAllowance: 400,
        grossEarnings: 9000,
        workingDays: 22,
        paidDays: 22,
        unpaidLeaveDays: 0,
        lopDeduction: 0,
        bonus: 800,
        incentives: 0,
        overtimePay: 0,
        pfDeduction: 450,
        insuranceDeduction: 150,
        otherDeductions: 50,
        taxDeduction: 1250,
        totalDeductions: 1900,
        netSalary: 7900,
        paymentStatus: "Paid",
        paymentMethod: "Bank Transfer",
        bankName: "Silicon Valley Bank",
        accountNumber: "•••• 4821",
      },
      {
        id: "pi-102",
        payrollRunId: "pr-2026-08",
        organizationId: "org-roacs",
        employeeId: "emp-102",
        employeeName: "David Chen",
        employeeCode: "RC-102",
        department: "Engineering",
        designation: "Senior Fullstack Engineer",
        basicSalary: 7500,
        hra: 2200,
        allowances: 800,
        specialAllowance: 500,
        grossEarnings: 11000,
        workingDays: 22,
        paidDays: 22,
        unpaidLeaveDays: 0,
        lopDeduction: 0,
        bonus: 1000,
        incentives: 0,
        overtimePay: 320,
        pfDeduction: 550,
        insuranceDeduction: 180,
        otherDeductions: 60,
        taxDeduction: 1680,
        totalDeductions: 2470,
        netSalary: 9850,
        paymentStatus: "Paid",
        paymentMethod: "Bank Transfer",
        bankName: "Chase Bank",
        accountNumber: "•••• 9143",
      },
      {
        id: "pi-103",
        payrollRunId: "pr-2026-08",
        organizationId: "org-roacs",
        employeeId: "emp-103",
        employeeName: "Liam O'Connor",
        employeeCode: "RC-103",
        department: "Engineering",
        designation: "QA Automation Engineer",
        basicSalary: 5200,
        hra: 1500,
        allowances: 500,
        specialAllowance: 300,
        grossEarnings: 7500,
        workingDays: 22,
        paidDays: 22,
        unpaidLeaveDays: 0,
        lopDeduction: 0,
        bonus: 400,
        incentives: 0,
        overtimePay: 150,
        pfDeduction: 380,
        insuranceDeduction: 140,
        otherDeductions: 40,
        taxDeduction: 980,
        totalDeductions: 1540,
        netSalary: 6510,
        paymentStatus: "Paid",
        paymentMethod: "Direct Deposit",
        bankName: "Wells Fargo",
        accountNumber: "•••• 3390",
      },
      {
        id: "pi-104",
        payrollRunId: "pr-2026-08",
        organizationId: "org-roacs",
        employeeId: "emp-104",
        employeeName: "Amira Patel",
        employeeCode: "RC-104",
        department: "Operations & HR",
        designation: "HR Operations Director",
        basicSalary: 6800,
        hra: 2000,
        allowances: 700,
        specialAllowance: 500,
        grossEarnings: 10000,
        workingDays: 22,
        paidDays: 22,
        unpaidLeaveDays: 0,
        lopDeduction: 0,
        bonus: 750,
        incentives: 0,
        overtimePay: 0,
        pfDeduction: 500,
        insuranceDeduction: 160,
        otherDeductions: 50,
        taxDeduction: 1420,
        totalDeductions: 2130,
        netSalary: 8620,
        paymentStatus: "Paid",
        paymentMethod: "Bank Transfer",
        bankName: "Bank of America",
        accountNumber: "•••• 7712",
      },
      {
        id: "pi-105",
        payrollRunId: "pr-2026-08",
        organizationId: "org-roacs",
        employeeId: "emp-105",
        employeeName: "Carlos Mendez",
        employeeCode: "RC-105",
        department: "Engineering",
        designation: "Junior Cloud Engineer",
        basicSalary: 4500,
        hra: 1200,
        allowances: 400,
        specialAllowance: 200,
        grossEarnings: 6300,
        workingDays: 22,
        paidDays: 21,
        unpaidLeaveDays: 1, // 1 day unpaid LOP = 4500 / 22 = $204.55
        lopDeduction: 205,
        bonus: 0,
        incentives: 0,
        overtimePay: 80,
        pfDeduction: 320,
        insuranceDeduction: 120,
        otherDeductions: 30,
        taxDeduction: 720,
        totalDeductions: 1395,
        netSalary: 4780,
        paymentStatus: "Paid",
        paymentMethod: "Bank Transfer",
        bankName: "Capital One",
        accountNumber: "•••• 6209",
      },
      {
        id: "pi-106",
        payrollRunId: "pr-2026-08",
        organizationId: "org-roacs",
        employeeId: "emp-106",
        employeeName: "Elena Rostova",
        employeeCode: "RC-106",
        department: "Sales & Growth",
        designation: "Senior Account Executive",
        basicSalary: 5800,
        hra: 1600,
        allowances: 600,
        specialAllowance: 400,
        grossEarnings: 8400,
        workingDays: 22,
        paidDays: 22,
        unpaidLeaveDays: 0,
        lopDeduction: 0,
        bonus: 1200,
        incentives: 950,
        overtimePay: 0,
        pfDeduction: 420,
        insuranceDeduction: 150,
        otherDeductions: 50,
        taxDeduction: 1350,
        totalDeductions: 1970,
        netSalary: 8580,
        paymentStatus: "Paid",
        paymentMethod: "Bank Transfer",
        bankName: "Citibank",
        accountNumber: "•••• 1984",
      },
      {
        id: "pi-107",
        payrollRunId: "pr-2026-08",
        organizationId: "org-roacs",
        employeeId: "emp-107",
        employeeName: "Michael Chang",
        employeeCode: "RC-107",
        department: "Finance & Legal",
        designation: "Finance Director",
        basicSalary: 8200,
        hra: 2400,
        allowances: 900,
        specialAllowance: 600,
        grossEarnings: 12100,
        workingDays: 22,
        paidDays: 22,
        unpaidLeaveDays: 0,
        lopDeduction: 0,
        bonus: 1500,
        incentives: 0,
        overtimePay: 0,
        pfDeduction: 600,
        insuranceDeduction: 200,
        otherDeductions: 70,
        taxDeduction: 1950,
        totalDeductions: 2820,
        netSalary: 10780,
        paymentStatus: "Paid",
        paymentMethod: "Bank Transfer",
        bankName: "JPMorgan Chase",
        accountNumber: "•••• 8234",
      },
      {
        id: "pi-108",
        payrollRunId: "pr-2026-08",
        organizationId: "org-roacs",
        employeeId: "emp-108",
        employeeName: "Rachel Kim",
        employeeCode: "RC-108",
        department: "Sales & Growth",
        designation: "Growth Marketing Specialist",
        basicSalary: 4800,
        hra: 1300,
        allowances: 450,
        specialAllowance: 250,
        grossEarnings: 6800,
        workingDays: 22,
        paidDays: 22,
        unpaidLeaveDays: 0,
        lopDeduction: 0,
        bonus: 300,
        incentives: 400,
        overtimePay: 0,
        pfDeduction: 350,
        insuranceDeduction: 130,
        otherDeductions: 40,
        taxDeduction: 910,
        totalDeductions: 1430,
        netSalary: 6070,
        paymentStatus: "Paid",
        paymentMethod: "Direct Deposit",
        bankName: "US Bank",
        accountNumber: "•••• 4410",
      },
    ],
  },
  {
    id: "pr-2026-09",
    organizationId: "org-roacs",
    month: "September",
    year: 2026,
    status: "Processing",
    totalEmployees: 8,
    workingDays: 21,
    grossPayroll: 50400,
    totalBonuses: 4800,
    totalDeductions: 13200,
    taxDeductions: 9250,
    netPayroll: 42000,
    processedAt: "2026-09-06T11:00:00Z",
    items: [],
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: "ann-1",
    organizationId: "org-roacs",
    title: "Q3 All-Hands Townhall & Executive Strategy Reveal",
    summary: "Join CEO and executive leadership for quarterly performance results, product roadmap unveil, and live Q&A.",
    content: `We are delighted to invite all team members to our upcoming **Q3 2026 Global All-Hands Townhall**.

### Agenda & Highlights:
1. **Executive Keynote**: Reviewing our record 142% year-over-year ARR milestone.
2. **Product Unveil**: Previewing the Next-Gen AI Talent Management engine.
3. **Open Q&A**: Live executive panel answering anonymous and live questions.

**Date**: Tuesday, Sep 8, 2026  
**Time**: 10:00 AM - 11:30 AM PT  
**Format**: Hybrid (San Francisco Auditorium & Zoom Stream)

*Catering and refreshments will be provided in the cafeteria immediately following the townhall.*`,
    featuredImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=60",
    category: "Company All-Hands",
    publishDate: "2026-09-02",
    audience: "Entire Company",
    priority: "Important",
    status: "Published",
    authorName: "Amira Patel",
    authorRole: "HR Operations Director",
    createdAt: "2026-09-02T08:00:00Z",
  },
  {
    id: "ann-2",
    organizationId: "org-roacs",
    title: "Updated Hybrid Work & Remote Office Reimbursement Policy",
    summary: "Effective Oct 1, eligible employees receive an upgraded $750 annual ergonomic equipment credit.",
    content: `People Operations is pleased to announce a significant enhancement to our workplace flexibility and home-office equipment stipend.

### Key Policy Upgrades:
- **Annual Ergonomic Home-Office Stipend**: Increased from $500 to **$750/year**.
- **Eligible Items**: Ergonomic desks, Herman Miller/Steelcase chairs, high-DPI monitors, noise-canceling headsets, and orthopedic wrist supports.
- **Claim Process**: Submit invoices through the *HR Management Portal > Expenses & Claims* tab with merchant receipt.

Please refer to the updated article in our Knowledge Base for complete vendor guidelines.`,
    category: "Policy Update",
    publishDate: "2026-09-05",
    audience: "Entire Company",
    priority: "Normal",
    status: "Published",
    authorName: "Amira Patel",
    authorRole: "HR Operations Director",
    createdAt: "2026-09-05T09:30:00Z",
  },
  {
    id: "ann-3",
    organizationId: "org-roacs",
    title: "Emergency Datacenter Maintenance & Security Drill",
    summary: "Scheduled infrastructure maintenance window this Saturday 02:00 AM - 04:00 AM UTC.",
    content: `The Infrastructure & Security Engineering team will conduct mandatory failover drills and kernel security patching on secondary database clusters.

**Impact**:
- Internal staging clusters and continuous integration pipelines will be temporarily paused.
- Customer-facing production services will maintain 99.99% active zero-downtime routing through regional mirrors.

If you encounter unexpected anomalies, ping the on-call channel in Slack: **#ops-incident-room**.`,
    category: "Health & Safety",
    publishDate: "2026-09-07",
    audience: "Department",
    audienceTargetName: "Engineering",
    priority: "Urgent",
    status: "Published",
    authorName: "David Chen",
    authorRole: "Senior Fullstack Engineer",
    createdAt: "2026-09-07T07:15:00Z",
  },
];

export const initialKnowledgeBaseCategories: KnowledgeBaseCategory[] = [
  { id: "cat-pol", organizationId: "org-roacs", name: "Company Policies", description: "Standard company rules, code of ethics, and workplace guidelines", iconName: "BuildingIcon", articleCount: 6 },
  { id: "cat-leave", organizationId: "org-roacs", name: "Leave & Attendance", description: "Holiday calendar, PTO allocation rules, and punch regularization", iconName: "LeaveTrackerIcon", articleCount: 4 },
  { id: "cat-sec", organizationId: "org-roacs", name: "IT Security & Compliance", description: "Device encryption, password managers, SOC2, and data protection", iconName: "GearIcon", articleCount: 5 },
  { id: "cat-remote", organizationId: "org-roacs", name: "Remote Work & Travel", description: "Travel allowances, per-diem rates, and co-working subsidies", iconName: "StarIcon", articleCount: 3 },
  { id: "cat-ben", organizationId: "org-roacs", name: "Employee Benefits & Health", description: "Medical insurance, 401(k) matching, dental, and wellness stipends", iconName: "TrophyIcon", articleCount: 4 },
  { id: "cat-onb", organizationId: "org-roacs", name: "Onboarding Playbook", description: "First 90 days milestone roadmap and tool directory for new joiners", iconName: "OnboardingIcon", articleCount: 3 },
];

export const initialKnowledgeBaseArticles: KnowledgeBaseArticle[] = [
  {
    id: "art-1",
    organizationId: "org-roacs",
    categoryId: "cat-pol",
    categoryName: "Company Policies",
    title: "Global Employee Code of Conduct & Ethics",
    content: `# Code of Conduct & Ethical Workplace Guidelines

### 1. Our Core Tenets
At Roacs Corporation, we uphold the highest standard of intellectual honesty, mutual respect, psychological safety, and inclusivity. Every employee, contractor, and leader is accountable for creating an environment where team members can thrive without prejudice or harassment.

### 2. Equal Opportunity & Zero Tolerance for Discrimination
We strictly prohibit any discrimination or harassment based on race, color, religion, sex, sexual orientation, gender identity, national origin, disability, or veteran status. Any violations are subject to immediate disciplinary action, up to and including termination without notice.

### 3. Conflict of Interest & External Advisory
Employees must disclose any external consulting, commercial investments, or board appointments that could represent an actual or perceived conflict of interest to the Legal & HR department.

### 4. Whistleblower Protection
Reports of ethical misconduct can be submitted anonymously through our encrypted hotline at \`compliance@roacscorp.com\`. Whistleblowers are protected from any form of retaliation under federal and state statute.`,
    tags: ["ethics", "conduct", "compliance", "legal"],
    attachmentName: "Code_of_Conduct_2026_Full.pdf",
    attachmentSize: "1.4 MB",
    version: "v3.2",
    publishedDate: "2026-01-15",
    lastUpdated: "2026-08-10",
    status: "Published",
    authorName: "Amira Patel",
    viewCount: 482,
  },
  {
    id: "art-2",
    organizationId: "org-roacs",
    categoryId: "cat-leave",
    categoryName: "Leave & Attendance",
    title: "Comprehensive Paid Time Off (PTO) & Leave Allocations",
    content: `# Paid Time Off & Leave Allocations Guide

### 1. Annual Allocation
Full-time personnel receive **15 Annual Leave days**, **10 Casual Leave days**, and **12 Sick Leave days** per calendar year.

### 2. Carry Forward Rules
- Up to **5 unused Annual Leave days** can be rolled over into the subsequent calendar year.
- Sick leave accrues on a monthly basis (1 day/month). Unused sick leaves up to 6 days carry forward.
- Casual leaves expire at midnight on December 31st and cannot be encashed or carried forward.

### 3. Loss of Pay (LOP) Computation
Leaves taken beyond approved allocations are classified as Unpaid Leave. Deduction is calculated strictly on basic compensation:
\`\`\`
Daily LOP Rate = Basic Monthly Salary / Working Days in Month
Total Deduction = Daily LOP Rate × Unpaid Days Taken
\`\`\`

### 4. Medical Certificates
Absences of 3 consecutive business days or more due to illness require a registered physician's certificate uploaded in the portal.`,
    tags: ["leave", "pto", "sick leave", "lop", "holidays"],
    attachmentName: "Leave_Policy_Handbook_v2.pdf",
    attachmentSize: "890 KB",
    version: "v2.4",
    publishedDate: "2026-02-01",
    lastUpdated: "2026-07-18",
    status: "Published",
    authorName: "Amira Patel",
    viewCount: 614,
  },
  {
    id: "art-3",
    organizationId: "org-roacs",
    categoryId: "cat-sec",
    categoryName: "IT Security & Compliance",
    title: "Information Security, Hardware Encryption & SOC2 Standards",
    content: `# Information Security & Clean Desk Policy

### 1. Workstation Security
- Full-disk encryption (FileVault for macOS, BitLocker for Windows) is **mandatory** on all machines accessing company repositories or databases.
- Screen timeout must be locked to **5 minutes or less**.

### 2. Multi-Factor Authentication (MFA)
Hardware security keys (YubiKey) or authenticator apps (1Password, Google Authenticator) are required for all SSO logins. SMS 2FA is prohibited for production cluster access.

### 3. Incident Escalation
If you suspect an active phishing attempt, lost laptop, or compromised credential, immediately contact **security@roacscorp.com** within 30 minutes.`,
    tags: ["security", "encryption", "soc2", "passwords", "it"],
    attachmentName: "IT_Security_Protocols_2026.pdf",
    attachmentSize: "2.1 MB",
    version: "v4.0",
    publishedDate: "2026-03-01",
    lastUpdated: "2026-08-25",
    status: "Published",
    authorName: "David Chen",
    viewCount: 390,
  },
  {
    id: "art-4",
    organizationId: "org-roacs",
    categoryId: "cat-ben",
    categoryName: "Employee Benefits & Health",
    title: "Health Insurance Coverage, 401(k) Match & Wellness Perks",
    content: `# Employee Benefits Program Summary

### 1. Health, Dental & Vision Coverage
Roacs Corporation pays **100% of premium costs** for full-time employees and **75% for dependents** via Anthem Blue Cross / Kaiser Permanente Platinum plans.

### 2. 401(k) Retirement Matching
The company matches **100% of the first 4%** and **50% of the next 2%** of eligible compensation, with immediate 100% vesting from Day 1.

### 3. Wellness & Mental Health
All team members have access to 12 free therapy sessions annually through Modern Health, plus a $50/month ClassPass or gym membership credit.`,
    tags: ["benefits", "insurance", "401k", "health", "wellness"],
    attachmentName: "Benefits_Enrollment_Guide_2026.pdf",
    attachmentSize: "3.2 MB",
    version: "v2.0",
    publishedDate: "2026-01-05",
    lastUpdated: "2026-06-12",
    status: "Published",
    authorName: "Amira Patel",
    viewCount: 540,
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "log-1",
    organizationId: "org-roacs",
    userId: "emp-104",
    userName: "Amira Patel",
    action: "PROCESSED_PAYROLL",
    module: "Payroll",
    recordId: "pr-2026-08",
    previousValue: "Status: Processing",
    newValue: "Status: Paid (Total Disbursed: $42,630.00)",
    ipAddress: "192.168.1.42",
    timestamp: "2026-08-31T18:00:00Z",
  },
  {
    id: "log-2",
    organizationId: "org-roacs",
    userId: "emp-104",
    userName: "Amira Patel",
    action: "OFFBOARDED_EMPLOYEE",
    module: "Employee",
    recordId: "emp-109",
    previousValue: "Status: Active, Role: DevOps Engineer",
    newValue: "Status: Offboarded, Assets Returned: Completed, Account Disabled",
    ipAddress: "192.168.1.42",
    timestamp: "2026-08-31T17:00:00Z",
  },
  {
    id: "log-3",
    organizationId: "org-roacs",
    userId: "emp-104",
    userName: "Amira Patel",
    action: "CREATED_ANNOUNCEMENT",
    module: "CMS",
    recordId: "ann-1",
    newValue: "Title: Q3 All-Hands Townhall (Audience: Entire Company)",
    ipAddress: "192.168.1.42",
    timestamp: "2026-09-02T08:00:00Z",
  },
  {
    id: "log-4",
    organizationId: "org-roacs",
    userId: "emp-102",
    userName: "David Chen",
    action: "APPROVED_LEAVE_REQUEST",
    module: "Leave Policy",
    recordId: "lr-102",
    previousValue: "Status: Pending",
    newValue: "Status: Approved (Carlos Mendez - 1 Day Sick Leave)",
    ipAddress: "192.168.1.18",
    timestamp: "2026-09-03T20:10:00Z",
  },
  {
    id: "log-5",
    organizationId: "org-roacs",
    userId: "emp-104",
    userName: "Amira Patel",
    action: "UPDATED_COMPANY_PROFILE",
    module: "Company Settings",
    recordId: "org-roacs",
    previousValue: "Address: Suite 300",
    newValue: "Address: 742 Innovation Way, Suite 400",
    ipAddress: "192.168.1.42",
    timestamp: "2026-09-04T11:25:00Z",
  },
];

export const initialNotifications: TenantNotification[] = [
  {
    id: "notif-1",
    organizationId: "org-roacs",
    title: "Pending Leave Request",
    message: "Sophia Williams submitted a 3-day Annual Leave request (Sep 8 - Sep 10).",
    category: "leave",
    read: false,
    timestamp: "25m ago",
    link: "/hr-dashboard/leave-tracker",
  },
  {
    id: "notif-2",
    organizationId: "org-roacs",
    title: "September Payroll Ready for Review",
    message: "September 2026 payroll run draft generated for 8 employees ($42,000 net).",
    category: "payroll",
    read: false,
    timestamp: "2h ago",
    link: "/hr-dashboard/payroll",
  },
  {
    id: "notif-3",
    organizationId: "org-roacs",
    title: "New Townhall Announcement Published",
    message: "Q3 All-Hands Townhall announcement was broadcasted to Entire Company.",
    category: "announcement",
    read: true,
    timestamp: "Yesterday",
    link: "/hr-dashboard/cms",
  },
  {
    id: "notif-4",
    organizationId: "org-roacs",
    title: "Work Anniversary Approaching",
    message: "Elena Rostova celebrates her 3rd work anniversary on Saturday, Sep 12.",
    category: "employee",
    read: true,
    timestamp: "2 days ago",
    link: "/hr-dashboard/employees",
  },
];

export const initialSubscriptionInvoices: SubscriptionInvoice[] = [
  { id: "inv-2026-08", organizationId: "org-roacs", invoiceNumber: "INV-RC-2026-08", date: "Aug 15, 2026", amount: 499, planName: "Professional Plan (Annual)", status: "Paid", pdfDownloadName: "Invoice_Aug_2026.pdf" },
  { id: "inv-2026-07", organizationId: "org-roacs", invoiceNumber: "INV-RC-2026-07", date: "Jul 15, 2026", amount: 499, planName: "Professional Plan (Annual)", status: "Paid", pdfDownloadName: "Invoice_Jul_2026.pdf" },
  { id: "inv-2026-06", organizationId: "org-roacs", invoiceNumber: "INV-RC-2026-06", date: "Jun 15, 2026", amount: 499, planName: "Professional Plan (Annual)", status: "Paid", pdfDownloadName: "Invoice_Jun_2026.pdf" },

  // Acme Invoices
  { id: "inv-acme-08", organizationId: "org-acme", invoiceNumber: "INV-AI-2026-08", date: "Aug 01, 2026", amount: 99, planName: "Starter Plan (Monthly)", status: "Paid", pdfDownloadName: "Invoice_Acme_Aug_2026.pdf" },
];

export const initialTimesheetCorrections: TimesheetCorrectionRequest[] = [
  {
    id: "corr-101",
    organizationId: "org-roacs",
    employeeId: "emp-105",
    employeeName: "Carlos Mendez",
    employeeAvatar: "CM",
    date: "2026-09-07",
    type: "Missing Punch-Out",
    requestedTime: "06:15 PM",
    reason: "DevOps production rollout extended past shift end. System auto-locked session before punch.",
    status: "Pending",
    appliedAt: "2026-09-07T19:40:00Z",
  },
  {
    id: "corr-102",
    organizationId: "org-roacs",
    employeeId: "emp-103",
    employeeName: "Liam O'Connor",
    employeeAvatar: "LO",
    date: "2026-09-06",
    type: "Late Regularization",
    originalTime: "09:34 AM",
    requestedTime: "09:00 AM",
    reason: "Client staging cluster outage triage from home between 8:30 AM - 9:15 AM before office transit.",
    status: "Pending",
    appliedAt: "2026-09-06T10:15:00Z",
  },
  {
    id: "corr-103",
    organizationId: "org-roacs",
    employeeId: "emp-108",
    employeeName: "Rachel Kim",
    employeeAvatar: "RK",
    date: "2026-09-04",
    type: "WFH Adjustment",
    requestedTime: "09:00 AM - 05:45 PM",
    reason: "Approved work-from-home research day, biometric kiosk not used.",
    status: "Pending",
    appliedAt: "2026-09-04T18:00:00Z",
  },
  {
    id: "corr-104",
    organizationId: "org-roacs",
    employeeId: "emp-105",
    employeeName: "Carlos Mendez",
    employeeAvatar: "CM",
    date: "2026-09-02",
    type: "Missing Punch-In",
    requestedTime: "08:50 AM",
    reason: "Building lobby badge gate was being serviced, entered via visitor reception escort.",
    status: "Approved",
    appliedAt: "2026-09-02T09:15:00Z",
    reviewedBy: "Sarah Chen",
    reviewedAt: "2026-09-02T10:30:00Z",
  },
];

export const initialTeamTimesheets: TeamMemberTimesheet[] = [
  {
    id: "ts-101",
    organizationId: "org-roacs",
    weekId: "2026-W36",
    weekRange: "Sep 01 - Sep 07, 2026",
    employeeId: "emp-103",
    employeeName: "Liam O'Connor",
    employeeAvatar: "LO",
    designation: "QA Automation Engineer",
    dailyHours: [
      { date: "2026-09-01", dayOfWeek: "Tue", hours: 8.5, checkIn: "08:55 AM", checkOut: "06:00 PM", status: "Regular" },
      { date: "2026-09-02", dayOfWeek: "Wed", hours: 8.0, checkIn: "09:00 AM", checkOut: "05:45 PM", status: "Regular" },
      { date: "2026-09-03", dayOfWeek: "Thu", hours: 9.0, checkIn: "08:45 AM", checkOut: "06:30 PM", status: "Overtime" },
      { date: "2026-09-04", dayOfWeek: "Fri", hours: 8.5, checkIn: "09:00 AM", checkOut: "06:05 PM", status: "Regular" },
      { date: "2026-09-05", dayOfWeek: "Sat", hours: 0, status: "Weekend" },
      { date: "2026-09-06", dayOfWeek: "Sun", hours: 0, status: "Weekend" },
      { date: "2026-09-07", dayOfWeek: "Mon", hours: 8.0, checkIn: "09:05 AM", checkOut: "06:10 PM", status: "Regular" },
    ],
    regularHours: 40.0,
    overtimeHours: 2.0,
    totalHours: 42.0,
    status: "Draft",
    hasDiscrepancy: false,
  },
  {
    id: "ts-102",
    organizationId: "org-roacs",
    weekId: "2026-W36",
    weekRange: "Sep 01 - Sep 07, 2026",
    employeeId: "emp-105",
    employeeName: "Carlos Mendez",
    employeeAvatar: "CM",
    designation: "Junior Cloud Engineer",
    dailyHours: [
      { date: "2026-09-01", dayOfWeek: "Tue", hours: 8.0, checkIn: "09:00 AM", checkOut: "05:45 PM", status: "Regular" },
      { date: "2026-09-02", dayOfWeek: "Wed", hours: 8.5, checkIn: "08:50 AM", checkOut: "06:00 PM", status: "Regular" },
      { date: "2026-09-03", dayOfWeek: "Thu", hours: 8.0, checkIn: "09:00 AM", checkOut: "05:45 PM", status: "Regular" },
      { date: "2026-09-04", dayOfWeek: "Fri", hours: 7.5, checkIn: "09:15 AM", checkOut: "05:15 PM", status: "Regular" },
      { date: "2026-09-05", dayOfWeek: "Sat", hours: 0, status: "Weekend" },
      { date: "2026-09-06", dayOfWeek: "Sun", hours: 0, status: "Weekend" },
      { date: "2026-09-07", dayOfWeek: "Mon", hours: 7.6, checkIn: "09:22 AM", checkOut: "06:00 PM", status: "Regular" },
    ],
    regularHours: 39.6,
    overtimeHours: 0,
    totalHours: 39.6,
    status: "Draft",
    hasDiscrepancy: true,
    discrepancyNote: "Late clock-in on Sep 07 and missing punch-out adjustment pending",
  },
  {
    id: "ts-103",
    organizationId: "org-roacs",
    weekId: "2026-W36",
    weekRange: "Sep 01 - Sep 07, 2026",
    employeeId: "emp-108",
    employeeName: "Rachel Kim",
    employeeAvatar: "RK",
    designation: "Growth Marketing Specialist",
    dailyHours: [
      { date: "2026-09-01", dayOfWeek: "Tue", hours: 8.0, checkIn: "09:00 AM", checkOut: "05:45 PM", status: "Regular" },
      { date: "2026-09-02", dayOfWeek: "Wed", hours: 8.0, checkIn: "08:55 AM", checkOut: "05:40 PM", status: "Regular" },
      { date: "2026-09-03", dayOfWeek: "Thu", hours: 8.5, checkIn: "09:00 AM", checkOut: "06:10 PM", status: "Regular" },
      { date: "2026-09-04", dayOfWeek: "Fri", hours: 8.0, checkIn: "09:00 AM", checkOut: "05:45 PM", status: "Regular" },
      { date: "2026-09-05", dayOfWeek: "Sat", hours: 0, status: "Weekend" },
      { date: "2026-09-06", dayOfWeek: "Sun", hours: 0, status: "Weekend" },
      { date: "2026-09-07", dayOfWeek: "Mon", hours: 0, status: "Leave" },
    ],
    regularHours: 32.5,
    overtimeHours: 0,
    totalHours: 32.5,
    status: "Verified",
    hasDiscrepancy: false,
    verifiedAt: "2026-09-08T09:15:00Z",
  },
];

export const initialTeamSpacePosts: TeamSpacePost[] = [
  {
    id: "tsp-1",
    organizationId: "org-roacs",
    category: "Goal",
    title: "🎯 Sprint 42: UI Platform Component Overhaul",
    content: "We are on track to wrap up Sprint 42 deliverables before the Friday release freeze. Major milestones include upgrading our shared UI table components, fixing responsive modal clipping, and achieving 95% test coverage.",
    authorName: "Sarah Chen",
    authorRole: "Frontend Tech Lead",
    authorAvatar: "SC",
    createdAt: "2026-09-08T09:30:00Z",
    priority: "Important",
    pinned: true,
    goalProgress: 78,
    goalTargetDate: "Sep 15, 2026",
    reactions: [
      { emoji: "🚀", count: 6, users: ["Liam O'Connor", "Carlos Mendez", "Rachel Kim", "David Chen"] },
      { emoji: "👍", count: 4, users: ["Sophia Williams", "Carlos Mendez"] },
    ],
    comments: [
      {
        id: "cm-1",
        authorName: "Liam O'Connor",
        authorRole: "QA Automation Engineer",
        authorAvatar: "LO",
        content: "End-to-end regression suites for the responsive layouts passed with zero critical flaws!",
        timestamp: "Yesterday at 4:30 PM",
      },
    ],
  },
  {
    id: "tsp-2",
    organizationId: "org-roacs",
    category: "Schedule",
    title: "📅 Next Week Shift Rotation & Weekend Staging Support",
    content: "Please review the updated shift schedules for Week 37. Core development hours remain 9:00 AM - 6:00 PM PST. Liam is handling primary triage during on-call rotation with Carlos as secondary backup.",
    authorName: "Sarah Chen",
    authorRole: "Frontend Tech Lead",
    authorAvatar: "SC",
    createdAt: "2026-09-07T14:15:00Z",
    priority: "Normal",
    pinned: false,
    scheduleDetails: {
      shiftName: "Engineering Shift A (General) & Triage",
      timing: "09:00 AM - 06:00 PM PST",
      rosterSummary: "5 Active Engineers + 1 Rotating On-Call Specialist",
      effectiveDates: "Sep 14 - Sep 20, 2026",
    },
    reactions: [
      { emoji: "👍", count: 5, users: ["Carlos Mendez", "Liam O'Connor", "Rachel Kim"] },
    ],
    comments: [],
  },
  {
    id: "tsp-3",
    organizationId: "org-roacs",
    category: "Recognition",
    title: "🏆 Team Shoutout: Carlos Mendez for Rapid Database Index Optimization!",
    content: "Huge kudos to Carlos for diagnosing our query latency bottleneck under simulated heavy load yesterday! Queries dropped from 1,200ms to 45ms. Outstanding problem-solving agility and dedication!",
    authorName: "Sarah Chen",
    authorRole: "Frontend Tech Lead",
    authorAvatar: "SC",
    createdAt: "2026-09-06T16:00:00Z",
    priority: "Important",
    pinned: false,
    targetEmployeeName: "Carlos Mendez",
    badge: "⚡ Speed Demon & Performance MVP",
    reactions: [
      { emoji: "👏", count: 8, users: ["Liam O'Connor", "Sarah Chen", "David Chen", "Rachel Kim", "Sophia Williams"] },
      { emoji: "🔥", count: 5, users: ["Amira Patel", "Michael Chang"] },
    ],
    comments: [
      {
        id: "cm-2",
        authorName: "Carlos Mendez",
        authorRole: "Junior Cloud Engineer",
        authorAvatar: "CM",
        content: "Thank you Sarah and everyone for the prompt code review and support!",
        timestamp: "Today at 10:15 AM",
      },
    ],
  },
];

